V = 0.2.6
EXEDIR =../bin
#
.PHONY: lib setup discrete
#
all: setup discrete
	
lib: 
	cd ../lib; make

discrete: lib
	make

install: all
	cp discrete $(EXEDIR)/discrete.exe

clean:
	cd lib;make clean
	cd make clean
	rm $(EXEDIR)/discrete.exe

        	
